integration:
  target: marko-dev
  outputs:
    marko-dev:
      type: postgres
      host: "ec2-18-215-109-218.compute-1.amazonaws.com"
      password: "pebdbca5144ec15a8733d21420f2b4ffe5f7f1a02328f7e4a245666dd00afdb66"
      user: "ubmn41dhvkc0tf"
      dbname: "dcbjia9bjs610n"
      schema: "public"
      port: 5432
      threads: 10 # max concurrent threads
